services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build: ./producer_service
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: podcast-files
      PODCASTS_DIR: /host_podcasts
    volumes:
      - /Users/elifisher/Downloads/podcasts:/host_podcasts:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  consumer:
    build: ./consumer_service
    depends_on:
      - kafka
      - elasticsearch
      - mongo
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: podcast-files
      ES_HOST: http://elasticsearch:9200
      ES_INDEX: podcasts_metadata
      MONGO_URI: mongodb://mongo:27017/
      MONGO_DB: podcasts_db
      MONGO_COLLECTION: podcasts_files
    volumes:
      - /Users/elifisher/Downloads/podcasts:/host_podcasts:ro

volumes:
  mongo_data: